version: "3"

services:
  pylint: 
    build: 'pylint/'
    volumes:
      - '../app:/app/'
  unittest: 
    build: 'docker-test/unittest/'
    volumes:
      - '../app:/app/'
  radon-cc: 
    build: 'docker-test/radon-cc/'
    volumes:
      - '../app:/app/'
  radon-raw: 
    build: 'docker-test/radon-raw/'
    volumes:
      - '../app:/app/'
  app:
    build: 
      context: '/home/joffreym2igcp/python-api-handle-it/'
      dockerfile: 'docker-app/python/Dockerfile'
    ports:
      - '5000:5000'
  robot:
    build: 'docker-test/robot/'
    environment:
      URL: 'app'
      PORT: '5000'
    depends_on: 
      - app
    volumes:
      - '../app:/app/'
